stages:
  - build
  - package
  - deploy

.ubuntu-18.04:
  tags: [ linux, docker ]
  image: git.imp.fu-berlin.de:5000/bioroboticslab/robofish/docker:devel-ubuntu18.04

.windows:
  tags: [ windows, docker ]
  image: git.imp.fu-berlin.de:5000/bioroboticslab/robofish/docker:devel-windows

.windows[cuda]:
  tags: [ windows, docker ]
  image: git.imp.fu-berlin.de:5000/bioroboticslab/robofish/docker:cuda-devel-windows

.gcc8: &gcc8
  CC: gcc-8
  CXX: g++-8

.msvc15.9: &msvc15_9
  VSDevEnv -arch=amd64 -vcvars_ver="14.16"

.pylon5: &pylon5
  WITH_PYLON5: 1

.debug: &debug
  CMAKE_BUILD_TYPE: Debug

.release: &release
  CMAKE_BUILD_TYPE: Release

.build ubuntu-18.04:
  extends: .ubuntu-18.04
  stage: build
  artifacts:
    paths:
      - vendor
      - build
    expire_in: 1 day
  script:
    - cmake -Bbuild -H. -DCMAKE_BUILD_TYPE="$CMAKE_BUILD_TYPE" -G Ninja -DCMAKE_SUPPRESS_REGENERATION=ON -DCMAKE_SKIP_PACKAGE_ALL_DEPENDENCY=ON
    - ninja -C build

.build windows:
  extends: .windows
  stage: build
  artifacts:
    paths:
      - vendor
      - build
    expire_in: 1 day
  script:
    - cmake -Bbuild "-H." -DCMAKE_BUILD_TYPE="$CMAKE_BUILD_TYPE" -G Ninja -DPACKAGE_WINDOWS_MSI=ON -DINSTALL_REQUIRED_SYSTEM_LIBRARIES=ON -DINSTALL_SHARED_LIBRARIES='flang;flangrti;libomp;zlib1;tiff;tiffxx;jpeg62;libpng16;lzma;openblas;boost_filesystem-vc141-mt-x64-1_68;boost_program_options-vc141-mt-x64-1_68;boost_system-vc141-mt-x64-1_68' -DINSTALL_OPENCV_COMPONENTS='core;calib3d;features2d;flann;highgui;imgcodecs;imgproc;ml;objdetect;photo;shape;stitching;superres;video;videoio;videostab;ffmpeg' -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_DIR/scripts/buildsystems/vcpkg.cmake" -DVCPKG_TARGET_TRIPLET="$env:VCPKG_TRIPLET" -DCMAKE_SUPPRESS_REGENERATION=ON -DCMAKE_SKIP_PACKAGE_ALL_DEPENDENCY=ON -DCPACK_PACKAGE_DIRECTORY="${env:PACKAGE_DIR}"
    - ninja -C build

build ubuntu-18.04:
  extends: .build ubuntu-18.04
  variables:
    <<: [ *gcc8, *release ]
  before_script:
    - . /etc/profile.d/robofish.sh
    - gitlab-fetch-artifacts bioroboticslab%2Fbiotracker%2Finterfaces master package%20ubuntu-18.04
    - cmake-integrate-package biotracker-interfaces
    - gitlab-fetch-artifacts bioroboticslab%2Fbiotracker%2Futility master package%20ubuntu-18.04
    - cmake-integrate-package biotracker-utility
    - gitlab-fetch-artifacts bioroboticslab%2Fbiotracker%2Fbehavior_loader master package%20ubuntu-18.04
    - cmake-integrate-package robofish-behavior_loader

build windows:
  extends: .build windows
  variables:
    <<: [ *release ]
  before_script:
    - . $Profile
    - *msvc15_9
    - GitLab-Fetch-Artifacts bioroboticslab%2Fbiotracker%2Finterfaces master package%20windows
    - CMake-Integrate-Package biotracker-interfaces
    - GitLab-Fetch-Artifacts bioroboticslab%2Fbiotracker%2Futility master package%20windows
    - CMake-Integrate-Package biotracker-utility
    - GitLab-Fetch-Artifacts bioroboticslab%2Fbiotracker%2Fbehavior_loader master package%20windows
    - CMake-Integrate-Package robofish-behavior_loader
    - $env:PACKAGE_DIR = ("${env:TMP}/pkg" -Replace "\\","/")
    - $env:PATH += ";${env:VCPKG_INSTALL_DIR}/bin"
    - $env:PATH += ";$(resolve-path vendor/biotracker-interfaces/bin)"

build windows[pylon5]:
  extends: .build windows
  variables:
    <<: [ *release, *pylon5 ]
  before_script:
    - . $Profile
    - *msvc15_9
    - GitLab-Fetch-Artifacts bioroboticslab%2Fbiotracker%2Finterfaces master package%20windows
    - CMake-Integrate-Package biotracker-interfaces
    - GitLab-Fetch-Artifacts bioroboticslab%2Fbiotracker%2Futility master package%20windows
    - CMake-Integrate-Package biotracker-utility
    - GitLab-Fetch-Artifacts bioroboticslab%2Fbiotracker%2Fbehavior_loader master package%20windows
    - CMake-Integrate-Package robofish-behavior_loader
    - $env:PACKAGE_DIR = ("${env:TMP}/pkg" -Replace "\\","/")
    - $env:PATH += ";${env:VCPKG_INSTALL_DIR}/bin"
    - $env:PATH += ";$(resolve-path vendor/biotracker-interfaces/bin)"

package ubuntu-18.04:
  extends: .ubuntu-18.04
  dependencies:
    - build ubuntu-18.04
  stage: package
  tags: [ linux, docker_privileged ]
  artifacts:
    paths:
      - build/*.AppImage
    expire_in: 1 week
  before_script:
    - . /etc/profile.d/robofish.sh
    - cmake-enable-package-discovery biotracker-interfaces
  script:
    - mkdir -p build/appdir/usr/bin
    - mkdir -p build/appdir/usr/share/applications
    - mkdir -p build/appdir/usr/share/icons/hicolor/256x256
    - cp build/Src/BioTracker build/appdir/usr/bin
    - cp Src/BioTracker.desktop build/appdir/usr/share/applications
    - cp Src/resources/logo/BT3-big.png build/appdir/usr/share/icons/hicolor/256x256
    - cd build
    - linuxdeployqt appdir/usr/share/applications/BioTracker.desktop -appimage -no-translations

.package windows:
  extends: .windows
  stage: package
  artifacts:
    paths:
      - build/*.msi
    expire_in: 1 week
  script:
    - ninja -C build package
    - Copy-Item "$env:PACKAGE_DIR/*" build -Recurse

package windows:
  extends: .package windows
  dependencies:
    - build windows
  before_script:
    - $env:PACKAGE_DIR = ("${env:TMP}/pkg" -Replace "\\","/")
    - $env:PATH += ";${env:VCPKG_INSTALL_DIR}/bin"
    - $env:PATH += ";$(resolve-path vendor/biotracker-interfaces/bin)"

package windows[pylon5]:
  extends: .package windows
  dependencies:
    - build windows[pylon5]
  before_script:
    - $env:PACKAGE_DIR = ("${env:TMP}/pkg" -Replace "\\","/")
    - $env:PATH += ";${env:VCPKG_INSTALL_DIR}/bin"
    - $env:PATH += ";$(resolve-path vendor/biotracker-interfaces/bin)"
